### PR TITLE
Contrast phase

### PR DESCRIPTION
**Pull request by edreisMD**
Hello World Pull Request

### CODE REVIEW

**Review by louisblankemeier — APPROVED** [review]
Looks good! Will need to clean up a bit but this is great! Will be so helpful to have this module here. Thank you!!

**Comment by akshaysc** [comment]
> good

**Comment by akshaysc** [comment]
Should we wait till the code is cleaned up prior to merging?

**Comment by louisblankemeier** [comment]
Code style is okay and passes the github action. @malteekj and I are meeting this weekend to discuss best practices for separating code into modules and after this discussion, several of us will probably have to go back and update our code. Different pipelines are fairly isolated so should be okay to update later. After we establish guidelines, we can make sure that code meets those guidelines before merging pull requests.

**Pull request merged**
